-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 21:07:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS GameTimeDB;
CREATE DATABASE IF NOT EXISTS GameTimeDB;
Use GameTimeDB;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `UserID` INT(9) NOT NULL,
  `Email` VARCHAR(90) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) INVISIBLE,
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User Profile` ;

CREATE TABLE IF NOT EXISTS `User Profile` (
  `ProfileID` INT(9) NOT NULL,
  `Avatar` VARCHAR(45) NULL,
  `FreeTime` TINYINT(2) NULL,
  `MultiplayerPreference` ENUM('Single', 'Coop', 'Large Scale') NULL,
  `SocialPlayPreference` ENUM('Light', 'Heavy', 'Optional') NULL,
  `User_UserID` INT(9) NOT NULL,
  PRIMARY KEY (`ProfileID`),
  INDEX `UserID_idx` (`User_UserID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) VISIBLE,
  UNIQUE INDEX `ProfileID_UNIQUE` (`ProfileID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game` ;

CREATE TABLE IF NOT EXISTS `Game` (
  `GameID` INT(9) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Complexity` TINYINT(2) NULL,
  `FocusLevel` TINYINT(2) NULL,
  `PlayMode` TINYINT(1) NULL DEFAULT 0,
  `Microtransactions` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`GameID`),
  UNIQUE INDEX `GameID_UNIQUE` (`GameID` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genre` ;

CREATE TABLE IF NOT EXISTS `Genre` (
  `GenreID` INT(9) NOT NULL,
  `GenreName` VARCHAR(45) NULL,
  `SubGenreName` VARCHAR(45) NULL,
  `SubGenreID` INT(9) NULL,
  PRIMARY KEY (`GenreID`),
  UNIQUE INDEX `GenreID_UNIQUE` (`GenreID` ASC) INVISIBLE,
  UNIQUE INDEX `SubGenreID_UNIQUE` (`SubGenreID` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameGenre` ;

CREATE TABLE IF NOT EXISTS `GameGenre` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Platform` ;

CREATE TABLE IF NOT EXISTS `Platform` (
  `PlatformID` INT(9) NOT NULL,
  `PlatformName` VARCHAR(45) NULL,
  `PlatformSpecificFeatures` VARCHAR(500) NULL,
  PRIMARY KEY (`PlatformID`),
  UNIQUE INDEX `PlatformID_UNIQUE` (`PlatformID` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_has_Platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game_has_Platform` ;

CREATE TABLE IF NOT EXISTS `Game_has_Platform` (
  `Game_GameID` INT(9) NOT NULL,
  `Platform_PlatformID` INT(9) NOT NULL,
  PRIMARY KEY (`Game_GameID`, `Platform_PlatformID`),
  INDEX `fk_Game_has_Platform_Platform1_idx` (`Platform_PlatformID` ASC) VISIBLE,
  INDEX `fk_Game_has_Platform_Game1_idx` (`Game_GameID` ASC) VISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) VISIBLE,
  UNIQUE INDEX `Platform_PlatformID_UNIQUE` (`Platform_PlatformID` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Platform_Game1`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Game_has_Platform_Platform1`
    FOREIGN KEY (`Platform_PlatformID`)
    REFERENCES `Platform` (`PlatformID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Review` ;

CREATE TABLE IF NOT EXISTS `Review` (
  `ReviewID` INT(9) NOT NULL,
  `Rating` TINYINT(3) NULL,
  `ReviewText` VARCHAR(1000) NULL,
  `TimeSpent` TINYINT(5) NULL,
  `Game_GameID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  PRIMARY KEY (`ReviewID`),
  UNIQUE INDEX `ReviewID_UNIQUE` (`ReviewID` ASC) INVISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `game_GameID`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event` ;

CREATE TABLE IF NOT EXISTS `Event` (
  `EventID` INT(9) NOT NULL,
  `EventDate` DATETIME NULL,
  `Description` VARCHAR(1000) NULL,
  `Game_GameID` INT(9) NOT NULL,
  PRIMARY KEY (`EventID`),
  INDEX `GameID_idx` (`Game_GameID` ASC) VISIBLE,
  UNIQUE INDEX `EventID_UNIQUE` (`EventID` ASC) INVISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) VISIBLE,
  CONSTRAINT `GameID`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Achivement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Achivement` ;

CREATE TABLE IF NOT EXISTS `Achivement` (
  `AchivementID` INT(9) NOT NULL,
  `AchivementDetails` VARCHAR(100) NULL,
  `Game_GameID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  PRIMARY KEY (`AchivementID`),
  INDEX `GameID_idx` (`Game_GameID` ASC) INVISIBLE,
  INDEX `UserID_idx` (`User_UserID` ASC) INVISIBLE,
  UNIQUE INDEX `AchivementID_UNIQUE` (`AchivementID` ASC) INVISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `GameID`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserGame` ;

CREATE TABLE IF NOT EXISTS `UserGame` (
  `OwnershipStatus` TINYINT(1) NULL DEFAULT 0,
  `WishlistStatus` TINYINT(1) NULL DEFAULT 0,
  `User_UserID` INT(9) NOT NULL,
  `Game_GameID` INT(9) NOT NULL,
  INDEX `GameID_idx` (`Game_GameID` ASC) INVISIBLE,
  INDEX `UserID_idx` (`User_UserID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) INVISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `GameID`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameGenre` ;

CREATE TABLE IF NOT EXISTS `GameGenre` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserGenrePreference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserGenrePreference` ;

CREATE TABLE IF NOT EXISTS `UserGenrePreference` (
  `User_UserID` INT(9) NOT NULL,
  `Genre_GenreID` INT(9) NOT NULL,
  `Genre_SubGenreID` INT(9) NULL,
  INDEX `GenreID_idx` (`Genre_GenreID` ASC) VISIBLE,
  INDEX `UserID_idx` (`User_UserID` ASC) VISIBLE,
  INDEX `SubGenreID_idx` (`Genre_SubGenreID` ASC) VISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) VISIBLE,
  UNIQUE INDEX `Genre_GenreID_UNIQUE` (`Genre_GenreID` ASC) VISIBLE,
  UNIQUE INDEX `Genre_SubGenreID_UNIQUE` (`Genre_SubGenreID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GenreID`
    FOREIGN KEY (`Genre_GenreID`)
    REFERENCES `Genre` (`GenreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SubGenreID`
    FOREIGN KEY (`Genre_SubGenreID`)
    REFERENCES `Genre` (`SubGenreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameUpdate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameUpdate` ;

CREATE TABLE IF NOT EXISTS `GameUpdate` (
  `UpdateID` INT(9) NOT NULL,
  `Game_GameID` INT(9) NOT NULL,
  `GameUpdatecol` VARCHAR(45) NULL,
  `UpdateDescription` VARCHAR(1000) NULL,
  `ReleaseDate` DATETIME NULL,
  PRIMARY KEY (`UpdateID`),
  INDEX `GameID_idx` (`Game_GameID` ASC) VISIBLE,
  UNIQUE INDEX `UpdateID_UNIQUE` (`UpdateID` ASC) INVISIBLE,
  UNIQUE INDEX `Game_GameID_UNIQUE` (`Game_GameID` ASC) INVISIBLE,
  CONSTRAINT `GameID`
    FOREIGN KEY (`Game_GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ContentModeration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ContentModeration` ;

CREATE TABLE IF NOT EXISTS `ContentModeration` (
  `ContentID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  `Approval` VARCHAR(45) NULL,
  `ApprovalDate` DATETIME NULL,
  `ContentType` VARCHAR(45) NULL,
  PRIMARY KEY (`ContentID`),
  INDEX `UserID_idx` (`User_UserID` ASC) VISIBLE,
  UNIQUE INDEX `ContentID_UNIQUE` (`ContentID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserReward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserReward` ;

CREATE TABLE IF NOT EXISTS `UserReward` (
  `RewardID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  `RewardType` VARCHAR(100) NULL,
  `EarnedDate` DATETIME NULL,
  PRIMARY KEY (`RewardID`),
  INDEX `UserID_idx` (`User_UserID` ASC) VISIBLE,
  UNIQUE INDEX `RewardID_UNIQUE` (`RewardID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNetwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNetwork` ;

CREATE TABLE IF NOT EXISTS `SocialNetwork` (
  `SocialNetworkID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  `SocialNetworkType` VARCHAR(45) NULL,
  `AccountDetails` VARCHAR(100) NULL,
  PRIMARY KEY (`SocialNetworkID`),
  INDEX `UserID_idx` (`User_UserID` ASC) VISIBLE,
  UNIQUE INDEX `SocialNetworkID_UNIQUE` (`SocialNetworkID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TechSupportTicket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TechSupportTicket` ;

CREATE TABLE IF NOT EXISTS `TechSupportTicket` (
  `TicketID` INT(9) NOT NULL,
  `User_UserID` INT(9) NOT NULL,
  `Issue` VARCHAR(1000) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`TicketID`),
  INDEX `UserID_idx` (`User_UserID` ASC) INVISIBLE,
  UNIQUE INDEX `TicketID_UNIQUE` (`TicketID` ASC) INVISIBLE,
  UNIQUE INDEX `User_UserID_UNIQUE` (`User_UserID` ASC) INVISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
